#spring.application.name=LogMetric-API
# PostgreSQL Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/logmetric
#spring.datasource.password=postgres

# Hibernate (ORM) Settings
# 'update' tells Spring to automatically build your SQL tables based on your Java classes
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.application.name=LogMetric-API

# =====================================================================
# 1. Managed Cloud PostgreSQL (Neon Singapore Edge)
# =====================================================================
spring.datasource.url=jdbc:postgresql://ep-still-rice-aogxmkr8.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2D9tSPYkeyVu

# Hibernate (ORM) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =====================================================================
# 2. Managed Cloud RabbitMQ Broker (CloudAMQP Cluster)
# =====================================================================
spring.rabbitmq.addresses=amqps://uiqapubs:OiLwHknjH3JHyCb0CNj02qCgwMmt5Z_b@armadillo.rmq.cloudamqp.com/uiqapubs